# Gitpod configuration
tasks:
  - name: Install Dependencies
    init: npm run install:all
    command: |
      cd backend && npx prisma generate
      npm run dev

ports:
  - port: 3001
    onOpen: ignore
    visibility: public
    name: Backend API
  - port: 5173
    onOpen: open-preview
    visibility: public
    name: Frontend

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - Prisma.prisma
